spring.application.name=kaizan-companion


telegram.bot.name=botforgo_bot
telegram.bot.token=${BOT_TOKEN}

#telegram https://api.telegram.org/bot<token>/METHOD_NAME
telegram.bot.api = https://api.telegram.org/bot${BOT_TOKEN}


DB_NAME=kaizan-db2
# Configuracoes do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Dialeto do Hibernate
## spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.dialect=org.hibernate.dialect.HSQLDialect

# Atualizar o banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=create

# Mostrar queries SQL no console
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Configuracoes adicionais
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver


storage.provider=${STORAGE_PROVIDER:local}
file.upload-dir=${FILE_UPLOAD_DIR:tmp}
